"""アプリケーションの定数定義"""

# App metadata
APP_NAME = "Study Agent"
APP_VERSION = "0.1.0"

# File size limits
MAX_FILE_SIZE_MB = 50
SUPPORTED_FORMATS = [".pdf"]

# Chunking
DEFAULT_CHUNK_SIZE = 1000
DEFAULT_CHUNK_OVERLAP = 200

# Quiz
DEAFULT_QUIZ_COUNT = 5
DEFAULT_QUIZ_DIFFICULTY = 3
MIN_DIFFICULTY = 1
MAX_DIFFICULTY = 5

# Progress
MASTERY_THRESHOLD = 80
WEAK_TOPIC_THRESHOLD = 50

# LLM
DEFAULT_MAX_TOKENS = 2048
DEFAULT_TEMPERATURE = 0.7
DEFAULT_TIMEOUT = 30
DEFAULT_MAX_RETRIES = 3

# Search
DEFAULT_TOP_K = 5
